[package]
name = "deser-secrecy"
version = "0.1.0"
description = "Deser support for secrecy types"
categories = ["encoding"]
keywords = ["deser", "utilities", "serialization", "deserialization"]
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
deser = { workspace = true }
secrecy = "0.10"

[dev-dependencies]
deser = { workspace = true, features = ["derive"] }
deser-json = { workspace = true }

[lints]
workspace = true
